#!/usr/bin/env/bash
#script displaying "Best School" unless variable is equal to 9, when it prints "Hi"
i=0
while [ $i -lt 10 ]
do
echo "Best School"
if [ $i -eq 8 ]
then
echo "Hi"
fi
i=$(( i + 1 ))
done
