#!/usr/bin/env bash
#Script that displays the time for 12 hours and 59 minutes.
hour=0
while [ $hour -lt 13 ]
do
	echo "Hours: $hour"
	min=1
	while [ $min -lt 60 ]
	do
		echo "Mins: $min"
		((min++))
	done
	((hour++))
done
